### ISSUE TITLE
After install show error to access port :3001

### ISSUE THREAD

**Issue by farhad-arjmand** [JasonBoy/vue-web-kit#1]
ERROR [1556026562276] (23054 on Farhads-MacBook-Pro.local): RequestError: connect ECONNREFUSED 127.0.0.1:3001
    at ClientRequest.request.once.error (/Users/farhad/Documents/Projects/Goftid/GWebApp/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:281:20)
    at ClientRequest.emit (events.js:198:15)
    at ClientRequest.origin.emit.args (/Users/farhad/Documents/Projects/Goftid/GWebApp/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Socket.socketErrorListener (_http_client.js:397:9)
    at Socket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
INFO  [1556026562276] (23054 on Farhads-MacBook-Pro.local): response body: undefined
ERROR [1556026562277] (23054 on Farhads-MacBook-Pro.local): ReferenceError: reject is not defined
    at DuplexWrapper.requestStream.on.error (/Users/farhad/Documents/Projects/Goftid/GWebApp/routes/proxy.js:26:11)
    at DuplexWrapper.emit (events.js:198:15)
    at EventEmitter.emitter.on.args (/Users/farhad/Documents/Projects/Goftid/GWebApp/node_modules/got/source/as-stream.js:69:58)
    at EventEmitter.emit (events.js:193:13)
    at emitError (/Users/farhad/Documents/Projects/Goftid/GWebApp/node_modules/got/source/request-as-event-emitter.js:43:12)
    at ClientRequest.request.once.error (/Users/farhad/Documents/Projects/Goftid/GWebApp/node_modules/got/source/request-as-event-emitter.js:182:6)
    at Object.onceWrapper (events.js:281:20)
    at ClientRequest.emit (events.js:198:15)
    at ClientRequest.origin.emit.args (/Users/farhad/Documents/Projects/Goftid/GWebApp/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Socket.socketErrorListener (_http_client.js:397:9)
    at Socket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
INFO  [1556026562277] (23054 on Farhads-MacBook-Pro.local): response body: undefined
(node:23054) UnhandledPromiseRejectionWarning: ReferenceError: reject is not defined
    at DuplexWrapper.requestStream.on.error (/Users/farhad/Documents/Projects/Goftid/GWebApp/routes/proxy.js:26:11)
    at DuplexWrapper.emit (events.js:198:15)
    at EventEmitter.emitter.on.args (/Users/farhad/Documents/Projects/Goftid/GWebApp/node_modules/got/source/as-stream.js:69:58)
    at EventEmitter.emit (events.js:193:13)
    at emitError (/Users/farhad/Documents/Projects/Goftid/GWebApp/node_modules/got/source/request-as-event-emitter.js:45:12)
    at ClientRequest.request.once.error (/Users/farhad/Documents/Projects/Goftid/GWebApp/node_modules/got/source/request-as-event-emitter.js:182:6)
    at Object.onceWrapper (events.js:281:20)
    at ClientRequest.emit (events.js:198:15)
    at ClientRequest.origin.emit.args (/Users/farhad/Documents/Projects/Goftid/GWebApp/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Socket.socketErrorListener (_http_client.js:397:9)
    at Socket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
(node:23054) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23054) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JasonBoy** [comment]
Fixed `ReferenceError: reject is not defined`, 
the 3001 error is because the Proxy config in your `app-config.js`, you can disable it with `NODE_PROXY: false` if you don't need it

**Comment by farhad-arjmand** [comment]
thanks 
howw i can use proxy , and config proxy for this app

**Comment by JasonBoy** [comment]
https://github.com/JasonBoy/vue-web-kit#application-config-and-environment-variables
